### ISSUE TITLE
ocamlfind: Package `git.unix' not found

### ISSUE THREAD

**Issue by talex5** [mirage/irmin#276]
Irmin tries to build `irmin-unix`, which depends on `git.unix`, if `flag(unix) && flag(http) && flag(git)`, where `opam` has:

      "--%{cohttp:enable}%-http"
      "--%{git:enable}%-git"
      "--%{base-unix:enable}%-unix"

But, `ocaml-git` builds `git.unix` if:

     "--%{conduit+cohttp+camlzip+nocrypto+base-unix:enable}%-unix"

Do you think it's worth splitting the Irmin package up a bit to avoid all these depopts?

**Comment by amirmc** [comment]
I had exactly the same issue this morning.

**Comment by samoht** [comment]
did you `opam update` I think I fixed that a few days ago

**Comment by amirmc** [comment]
I'm on a fresh install of everything as of yesterday night. I did run opam update before doing anything though.

I think I ‘fixed' my issue by installing camlzip

**Comment by dsheets** [comment]
This still exists and breaks other people's revdeps: <https://travis-ci.org/mirage/ocaml-dns/jobs/84652262#L1593>

**Comment by yallop** [comment]
It'd be useful to have a `git-unix` virtual package that depended on the packages needed to trigger `--enable-unix`.

**Comment by yallop** [comment]
[More brokenness with Irmin 0.9.9](https://travis-ci.org/ocaml/opam-repository/jobs/85092686) (see https://github.com/ocaml/opam-repository/pull/4977 for context):

```
#=== ERROR while installing irmin.0.9.9 =======================================#
# opam-version 1.2.2
# os           linux
# command      ./configure --prefix /home/travis/.opam/system --enable-http --enable-git --enable-unix --disable-mirage
# path         /home/travis/.opam/system/build/irmin.0.9.9
# compiler     system (4.02.3)
# exit-code    1
# env-file     /home/travis/.opam/system/build/irmin.0.9.9/irmin-8084-6b35cd.env
# stdout-file  /home/travis/.opam/system/build/irmin.0.9.9/irmin-8084-6b35cd.out
# stderr-file  /home/travis/.opam/system/build/irmin.0.9.9/irmin-8084-6b35cd.err
### stderr ###
# ocamlfind: Package `git.unix' not found
# W: Field 'pkg_git_unix' is not set: Command ''/home/travis/.opam/system/bin/ocamlfind' query -format %d git.unix > '/tmp/oasis-abbc01.txt'' terminated with error code 2
# E: Cannot find findlib package git.unix
# E: Failure("1 configuration error")
```

**Comment by samoht** [comment]
> It'd be useful to have a git-unix virtual package that depended on the packages needed to trigger --enable-unix.

that would be very helpful indeed. Can someone do that?

**Comment by samoht** [comment]
> that would be very helpful indeed. Can someone do that?

Actually I'll do it now. That'll simplify the current mess greatly.

**Comment by samoht** [comment]
See #4985 and #4986

**Comment by samoht** [comment]
> Do you think it's worth splitting the Irmin package up a bit to avoid all these depopts?

yes!

**Comment by avsm** [comment]
Agreed. Probably should do the same with cohttp.

**Comment by talex5** [comment]
Broken again - fix lost in 0.10.0 release?

    Processing 44/44: [irmin: ocamlfind remove]
    #=== ERROR while installing irmin.0.10.0 ======================================#
    # opam-version 1.2.2
    # os           linux
    # command      ./configure --prefix /home/travis/.opam/system --enable-http --enable-git --enable-unix --enable-mirage
    # path         /home/travis/.opam/system/build/irmin.0.10.0
    # compiler     system (4.02.3)
    # exit-code    1
    # env-file     /home/travis/.opam/system/build/irmin.0.10.0/irmin-10226-42eb96.env
    # stdout-file  /home/travis/.opam/system/build/irmin.0.10.0/irmin-10226-42eb96.out
    # stderr-file  /home/travis/.opam/system/build/irmin.0.10.0/irmin-10226-42eb96.err
    ### stderr ###
    # ocamlfind: Package `git.unix' not found
    # W: Field 'pkg_git_unix' is not set: Command ''/home/travis/.opam/system/bin/ocamlfind' query -format %d git.unix > '/tmp/oasis-876e96.txt'' terminated with error code 2
    # E: Cannot find findlib package git.unix
    # E: Failure("1 configuration error")
